### PR TITLE
Export filtered

### PR DESCRIPTION
**Pull request by Benvii**
Adding export endpoint, to handle filtered export.

### CODE REVIEW

**Comment by Benvii** [comment]
Up
This is an all PR if someone can review it, it would be great.
Tkx

**Comment by Benvii** [comment]
up @zyioump @Valdimus

**Review by zyioump — DISMISSED** [review]
export don't work when dm-cols is empty

**Review by Benvii — COMMENTED** [review]
Good :)

**Comment by Benvii** [comment]
I'm the author of this PR I can't approve it, @Valdimus can you review it ?

**Review by Valdimus — COMMENTED** [review]
Seems OK

**Review by Valdimus — APPROVED** [review]
Let's go to merge it

**Pull request merged**
