### PR TITLE
39 38 new model with path virtualtours

### PR DESCRIPTION
**Pull request by Benvii**
New database model with graph and virtualtours.

### CODE REVIEW

**Comment by Benvii** [comment]
Problem on requests on path_details creation : 
```
curl -X POST \
  http://opv_master:5000/v1/path_details \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '{
	"name": "My first path",
	"description": "I love making paths",
	"campaign": {
		"id_campaign": 1,
		"id_malette": 42
	}
}'
```
Gives an error : 
```
"Sqlalchemy didn't like it <class 'sqlalchemy.exc.DataError'>"
```

**Comment by Benvii** [comment]
The above error was fixed in 2b1f0cf

**Comment by Benvii** [comment]
Still need to fix #44 before accepting this PR.

**Review by zyioump — APPROVED** [review]
Good

**Pull request merged**
